### ISSUE TITLE
error during install: `python setup.py bdist_wheel did not run sucessfully`

### ISSUE THREAD

**Issue by nl835** [dpryan79/py2bit#15]
When installing deeptools, it seems to keep failing due to py2bit, so I attempted installing py2bit alone first to see if it was the one causing problems.

when running `pip install py2bit`, it throws the following error: 

Collecting py2bit
  Using cached py2bit-0.3.0.tar.gz (16 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: py2bit
  Building wheel for py2bit (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [45 lines of output]
      /home/nickylauw/anaconda3/lib/python3.12/site-packages/setuptools/dist.py:452: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!
      
              ********************************************************************************
              Usage of dash-separated 'description-file' will not be supported in future
              versions. Please use the underscore name 'description_file' instead.
      
              By 2024-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        opt = self.warn_dash_deprecation(opt, section)
      /home/nickylauw/anaconda3/lib/python3.12/site-packages/setuptools/_distutils/dist.py:260: UserWarning: Unknown distribution option: 'classifier'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-312
      creating build/lib.linux-x86_64-cpython-312/py2bitTest
      copying py2bitTest/__init__.py -> build/lib.linux-x86_64-cpython-312/py2bitTest
      copying py2bitTest/test.py -> build/lib.linux-x86_64-cpython-312/py2bitTest
      running egg_info
      writing py2bit.egg-info/PKG-INFO
      writing dependency_links to py2bit.egg-info/dependency_links.txt
      writing top-level names to py2bit.egg-info/top_level.txt
      reading manifest file 'py2bit.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE.txt'
      writing manifest file 'py2bit.egg-info/SOURCES.txt'
      copying py2bitTest/foo.2bit -> build/lib.linux-x86_64-cpython-312/py2bitTest
      running build_ext
      building 'py2bit' extension
      creating build/temp.linux-x86_64-cpython-312
      creating build/temp.linux-x86_64-cpython-312/lib2bit
      gcc -pthread -B /home/nickylauw/anaconda3/compiler_compat -fno-strict-overflow -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/nickylauw/anaconda3/include -fPIC -O2 -isystem /home/nickylauw/anaconda3/include -fPIC -Ilib2bit -I/home/nickylauw/anaconda3/include/python3.12 -I/home/nickylauw/anaconda3/include/python3.12 -c lib2bit/2bit.c -o build/temp.linux-x86_64-cpython-312/lib2bit/2bit.o
      gcc -pthread -B /home/nickylauw/anaconda3/compiler_compat -fno-strict-overflow -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/nickylauw/anaconda3/include -fPIC -O2 -isystem /home/nickylauw/anaconda3/include -fPIC -Ilib2bit -I/home/nickylauw/anaconda3/include/python3.12 -I/home/nickylauw/anaconda3/include/python3.12 -c py2bit.c -o build/temp.linux-x86_64-cpython-312/py2bit.o
      py2bit.c: In function ‘py2bitEnter’:
      py2bit.c:35:24: error: initialization of ‘pyTwoBit_t *’ from incompatible pointer type ‘TwoBit *’ [-Wincompatible-pointer-types]
         35 |     pyTwoBit_t *pytb = self->tb;
            |                        ^~~~
      error: command '/sbin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for py2bit
  Running setup.py clean for py2bit
Failed to build py2bit
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (py2bit)

Installing with `pip install git+https://github.com/dpryan79/py2bit` returns the same error. 

Installing with conda install bioconda::py2bit is stuck for very long with the following message until I interrupt with ctrl + C

Collecting package metadata (current_repodata.json): - WARNING conda.models.version:get_matcher(563): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.7.1.*, but conda is ignoring the .* and treating it as 1.7.1
done
Solving environment: - unsuccessful initial attempt using frozen solve. Retrying with flexible solve.

OS: Arch linux
Python version: 3.12.2
pip version: 24.2
conda version: 24.7.1

**Comment by dpryan79** [comment]
This should now be fixed in version 0.3.2, please let me know if not!
