### ISSUE TITLE
Installation issue (zip_safe)

### ISSUE THREAD

**Issue by eranroz** [dpryan79/py2bit#3]
When installing deepTools with python 3.5, that has py2bit dependency I see the following error.

> 
> Searching for py2bit>=0.2.0
> Reading https://pypi.python.org/simple/py2bit/
> Downloading https://pypi.python.org/packages/f4/98/5fc4799e9b6717a80aa31efd09bb6ce8fbca87fae8985ca202129639ff24/py2bit-0.2.0.tar.gz#md5=c441eea85270dda8f502b389b6235518
> Best match: py2bit 0.2.0
> Processing py2bit-0.2.0.tar.gz
> Writing /tmp/easy_install-0_f14xfi/py2bit-0.2.0/setup.cfg
> Running py2bit-0.2.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-0_f14xfi/py2bit-0.2.0/egg-dist-tmp-hkoejrrm
> /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'classifier'
>   warnings.warn(msg)
> zip_safe flag not set; analyzing archive contents...
> py2bitTest.__pycache__.test.cpython-35: module references __file__
> __pycache__.py2bit.cpython-35: module references __file__
> No eggs found in /tmp/easy_install-0_f14xfi/py2bit-0.2.0/egg-dist-tmp-hkoejrrm (setup script problem?)
> error: The 'py2bit>=0.2.0' distribution was not found and is required by deepTools

**Comment by dpryan79** [comment]
```
$ pip3 --version
pip 9.0.1 from /home/dpryan/.local/lib/python3.5/site-packages (python 3.5)
$ pip3 install --user --upgrade py2bit
Collecting py2bit
  Downloading py2bit-0.2.0.tar.gz
Building wheels for collected packages: py2bit
  Running setup.py bdist_wheel for py2bit ... done
  Stored in directory: /home/dpryan/.cache/pip/wheels/3b/8a/75/515e699d438777e6c12d36abbf2126579fdfac9633bc2d1940
Successfully built py2bit
Installing collected packages: py2bit
Successfully installed py2bit-0.2.0
```

Seems to work fine. Also, the bioconda python3 package builds fine, so presumably your python installation has problems.

**Comment by eranroz** [comment]
Thank you for the quick response. Solved (seems that the issue due to old pip [version 8.1.2] with some broken pip configurations)

**Comment by dpryan79** [comment]
Glad it was an easy fix :)
