### ISSUE TITLE
segmentation fault when reading sequence from ucsc hg38.2bit

### ISSUE THREAD

**Issue by newgene** [dpryan79/py2bit#4]
Thanks for making py2bit available. Just gave it a try on UCSC hg38.2bit file (downloaded [here](http://hgdownload.cse.ucsc.edu/goldenPath/hg38/bigZips/)), but got segmentation fault after a few tries:
```
Python 3.5.2 (default, Jul  5 2016, 12:43:10)
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import py2bit

In [2]: tb = py2bit.open('~/Downloads/hg38.2bit')

In [3]: tb.sequence('chrX', 101349952, 101349954)
Out[3]: 'CT'

In [4]: tb.sequence('chrX', 101349952, 101349955)
Out[4]: 'CTT'

In [5]: tb.sequence('chrX', 101349953, 101349955)
[1]    2094 segmentation fault (core dumped)  ipython
```

The latest py2bit==0.2.0 was installed. Verified the same on Python 2.7.12.

**Comment by dpryan79** [comment]
I think I have a fix for this, I'll test it more tomorrow to be sure and then release it as version 0.2.1. I've never needed to get so few bases, so I never tested this particular use-case.

**Comment by dpryan79** [comment]
I have an automated test for this now. I'll release version 0.2.1 this weekend, which will include this fix.
