### ISSUE TITLE
.sequence does not work well with int64

### ISSUE THREAD

**Issue by daquang** [dpryan79/py2bit#7]
When I use the .sequence function, and start and/or stop are int64, I get this error:
RuntimeError: You must supply at least a chromosome!
The error disappears if I make sure to typecast to int before I call .sequence.

**Comment by dpryan79** [comment]
I never wrote the functions to deal with int64s, since the format doesn’t handle bigger than an int32 to begin with. I can modify that next week.

**Comment by dpryan79** [comment]
4 years later I obviously didn't get around to doing this "next week". Since the format uses max int32 coordinates, I'm OK with not allowing int64 values to be used.
